### PR TITLE
Fix change detection issues from #107

### PR DESCRIPTION
**Pull request by eyuelt**
…to figure out root cause.

### CODE REVIEW

**Comment by girum11** [comment]
LGTM

**Comment by eyuelt** [comment]
This finally fixes #107

**Comment by girum11** [comment]
Too perfect.

LGTM

**Comment by girum11** [comment]
LGTM

**Comment by girum11** [comment]
LGTM!!!!

(looks like lgtm.co is broken?)

**Comment by eyuelt** [comment]
LGTM

**Comment by eyuelt** [comment]
👍

**Pull request merged**
